version: '3.1'

services:
  node:
    container_name: node-mysql
    restart: always
    build: .
    ports:
      - 3001:3001
    links:
      - mysql
    volumes:
      - .:/usr/src/app
  mysql:
    container_name: mysql-db
    image: mysql
    # security_opt:
    #   - seccomp:unconfined
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: Blogs
    logging:
      driver: none
